### PR TITLE
Use emoji codes

### PR DESCRIPTION
**Pull request by prabhu**

### CODE REVIEW

**Review by fabsx00 — APPROVED** [review]

**Comment by gitnachogo** [comment]
Hi @prabhu ! I think this is failing in GitLab! Could you check this?
Capture d’écran 2020-11-13 134154

**Comment by prabhu** [comment]
@gitnachogo Pushed out a fix now. Can you retry the build and see how it looks?

**Comment by gitnachogo** [comment]
That works fine now, thanks!! So quick you are 😄

**Comment by mschfh** [comment]
Hi @prabhu,

seems broken with GitHub Actions too:
image

**Comment by prabhu** [comment]
Damn. Let me push a fix!

**Pull request merged**
